version: "24.0.7"
services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env_non_dev
    ports:
      - "9588:5432"
    restart: always


  redis:
    image: redis:7
    container_name: redis_app


  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 7077:8088
    env_file:
      - .env_non_dev
    depends_on:
      - db
      - redis


  celery:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis


  flower:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555

#  socket:
#    build:
#      context: .
#    container_name: socket_app
#    ports:
#      - 5008:5008